
"use client";

import "./globals.css";
import { usePathname } from "next/navigation";
import Header from "../components/header/header";
// import Footer from "@/components/footer/footer";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname(); // Get the current route
  const isAdminPage = pathname.startsWith("/admin"); // Check if it's an admin page

  return (
    <html lang="en">
      <body className="antialiased bg-white min-h-screen overflow-x-hidden min-w-screen ">
        {/* Show Header only if not on an admin page */}
        {!isAdminPage && <Header />}
        {children}
      </body>
    </html>
  );
}
